#!/bin/bash

# Determine the user's home directory using 'getent' command and 'grep'
home_dir=$(getent passwd "$USER" | cut -d: -f6)

# Change the working directory to the user's home directory
cd "$home_dir"
